---
title: "preprocessing"
author: "Ntels_BI_song"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_height: 6
    keep_md: no
    theme: yeti
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r env, echo = F, warning = F, message = F}
pacman::p_load(knitr, tidyverse, ggplot2, lubridate, tidyr, dplyr, data.table, RMySQL, zoo)
opts_chunk$set(fig.path = "output/figure/", fig.align = "center", out.width = "85%", warning = F, message = F)
theme_set(theme_bw(base_family = "FreeMono")); scriptEcho = T
```

<br><br>

## ETL preprocessing

```{r eval = T, echo = scriptEcho}
con <- dbConnect(MySQL(), host = "219.250.188.145", user = "dems", password = "dems123#", dbname = "demsdb")
query <- "select * from data_sample_fix where tagId in ('EL-2F-U.A1.AI84', 'EL-2F-U.B1.AI84', 'EL-2F-U.A2.AI84', 'EL-2F-U.B2.AI84', 'EL-2F-U.A3.AI84', 'EL-2F-U.B3.AI84', 'EL-2F-U.A4.AI84', 'EL-2F-U.B4.AI84', 'EL-2F-U.A5.AI84', 'EL-2F-U.B5.AI84', 'EL-2F-U.A6.AI84', 'EL-2F-U.B6.AI84', 'EL-2F-U.A7.AI84', 'EL-2F-U.B7.AI84', 'EL-2F-U.A8.AI84', 'EL-2F-U.B8.AI84', 'EL-2F-U.A9.AI84', 'EL-2F-U.B9.AI84', 'EL-2F-U.A10.AI84', 'EL-2F-U.B10.AI84', 'EL-2F-U.A11.AI84', 'EL-2F-U.B11.AI84', 'EL-P2.A-1.AI17', 'EL-P2.A-2.AI17', 'EL-P2.A-3.AI17', 'EL-P2.A-4.AI17', 'EL-P2.A-5.AI17', 'EL-P2.B-1.AI17', 'EL-P2.B-2.AI17', 'EL-P2.B-3.AI17', 'EL-P2.B-4.AI17', 'EL-P2.B-5.AI17', 'EL.LN-2A.AI58', 'BAS.2F-CRAC.1.temp', 'BAS.2F-CRAC.1.humi', 'BAS.2F-CRAC.1.temp_s', 'BAS.2F-CRAC.1.humi_s', 'BAS.2F-CRAC.2.temp', 'BAS.2F-CRAC.2.humi', 'BAS.2F-CRAC.2.temp_s', 'BAS.2F-CRAC.2.humi_s', 'BAS.2F-CRAC.3.temp', 'BAS.2F-CRAC.3.humi', 'BAS.2F-CRAC.3.temp_s', 'BAS.2F-CRAC.3.humi_s', 'BAS.2F-CRAC.4.temp', 'BAS.2F-CRAC.4.humi', 'BAS.2F-CRAC.4.temp_s', 'BAS.2F-CRAC.4.humi_s', 'BAS.2F-CRAC.5.temp', 'BAS.2F-CRAC.5.humi', 'BAS.2F-CRAC.5.temp_s', 'BAS.2F-CRAC.5.humi_s', 'BAS.2F-CRAC.6.temp', 'BAS.2F-CRAC.6.humi', 'BAS.2F-CRAC.6.temp_s', 'BAS.2F-CRAC.6.humi_s', 'BAS.2F-CRAC.7.temp', 'BAS.2F-CRAC.7.humi', 'BAS.2F-CRAC.7.temp_s', 'BAS.2F-CRAC.7.humi_s', 'BAS.2F-CRAC.8.temp', 'BAS.2F-CRAC.8.humi', 'BAS.2F-CRAC.8.temp_s', 'BAS.2F-CRAC.8.humi_s', 'BAS.2F-CRAC.9.temp', 'BAS.2F-CRAC.9.humi', 'BAS.2F-CRAC.9.temp_s', 'BAS.2F-CRAC.9.humi_s', 'BAS.2F-CRAC.10.temp', 'BAS.2F-CRAC.10.humi', 'BAS.2F-CRAC.10.temp_s', 'BAS.2F-CRAC.10.humi_s', 'BAS.2F-CRAC.11.temp', 'BAS.2F-CRAC.11.humi', 'BAS.2F-CRAC.11.temp_s', 'BAS.2F-CRAC.11.humi_s', 'BAS.2F-CRAC.12.temp', 'BAS.2F-CRAC.12.humi', 'BAS.2F-CRAC.12.temp_s', 'BAS.2F-CRAC.12.humi_s', 'BAS.2F-CRAC.13.temp', 'BAS.2F-CRAC.13.humi', 'BAS.2F-CRAC.13.temp_s', 'BAS.2F-CRAC.13.humi_s', 'BAS.2F-CRAC.14.temp', 'BAS.2F-CRAC.14.humi', 'BAS.2F-CRAC.14.temp_s', 'BAS.2F-CRAC.14.humi_s', 'BAS.2F-CRAC.15.temp', 'BAS.2F-CRAC.15.humi', 'BAS.2F-CRAC.15.temp_s', 'BAS.2F-CRAC.15.humi_s', 'BAS.2F-CRAC.16.temp', 'BAS.2F-CRAC.16.humi', 'BAS.2F-CRAC.16.temp_s', 'BAS.2F-CRAC.16.humi_s', 'BAS.2F-CRAC.17.temp', 'BAS.2F-CRAC.17.humi', 'BAS.2F-CRAC.17.temp_s', 'BAS.2F-CRAC.17.humi_s', 'BAS.2F-CRAC.18.temp', 'BAS.2F-CRAC.18.humi', 'BAS.2F-CRAC.18.temp_s', 'BAS.2F-CRAC.18.humi_s', 'BAS.2F-CRAC.19.temp', 'BAS.2F-CRAC.19.humi', 'BAS.2F-CRAC.19.temp_s', 'BAS.2F-CRAC.19.humi_s', 'BAS.2F-CRAC.20.temp', 'BAS.2F-CRAC.20.humi', 'BAS.2F-CRAC.20.temp_s', 'BAS.2F-CRAC.20.humi_s', 'BAS.CT-12.AI1', 'BAS.CT-12.AI2', 'BAS.CT-12.AI3', 'BAS.CT-10.AI5', 'BAS.CT-12.AI4', 'BAS.CT-10.AI7', 'BAS.EXT.temp', 'BAS.EXT.humi', 'SENSOR.IN.AI1', 'SENSOR.IN.AI2', 'SENSOR.IN.AI3', 'SENSOR.IN.AI4', 'SENSOR.IN.AI5', 'SENSOR.IN.AI6', 'SENSOR.IN.AI7', 'SENSOR.IN.AI8', 'SENSOR.IN.AI9', 'SENSOR.IN.AI10', 'SENSOR.IN.AI11', 'SENSOR.IN.AI12', 'SENSOR.IN.AI13', 'SENSOR.IN.AI14', 'SENSOR.IN.AI15', 'SENSOR.IN.AI16', 'SENSOR.IN.AI17', 'SENSOR.IN.AI18', 'SENSOR.IN.AI19', 'SENSOR.IN.AI20', 'SENSOR.IN.AI21', 'SENSOR.IN.AI22', 'SENSOR.IN.AI23', 'SENSOR.IN.AI24', 'SENSOR.IN.AI25', 'SENSOR.IN.AI26', 'SENSOR.IN.AI27', 'SENSOR.IN.AI28', 'SENSOR.IN.AI29', 'SENSOR.IN.AI30', 'SENSOR.IN.AI31', 'SENSOR.IN.AI32', 'SENSOR.IN.AI33', 'SENSOR.IN.AI34', 'SENSOR.IN.AI35', 'SENSOR.IN.AI36', 'SENSOR.IN.AI37', 'SENSOR.IN.AI38', 'SENSOR.IN.AI39', 'SENSOR.IN.AI40', 'SENSOR.IN.AI41', 'SENSOR.IN.AI42', 'SENSOR.IN.AI43', 'SENSOR.IN.AI44', 'SENSOR.IN.AI45', 'SENSOR.IN.AI46', 'SENSOR.IN.AI47', 'SENSOR.IN.AI48', 'SENSOR.IN.AI49', 'SENSOR.IN.AI50', 'SENSOR.IN.AI51', 'SENSOR.IN.AI52', 'SENSOR.IN.AI53', 'SENSOR.IN.AI54', 'SENSOR.IN.AI55', 'SENSOR.IN.AI56', 'SENSOR.IN.AI57', 'SENSOR.IN.AI58', 'SENSOR.IN.AI59', 'SENSOR.IN.AI60', 'SENSOR.IN.AI61', 'SENSOR.IN.AI62', 'SENSOR.IN.AI63', 'SENSOR.IN.AI64', 'SENSOR.IN.AI65', 'SENSOR.IN.AI66', 'SENSOR.IN.AI67', 'SENSOR.IN.AI68', 'SENSOR.IN.AI69', 'SENSOR.IN.AI70')" # TODO : 모든데이터를 가져오는 것이 아닌 예를들면 최근 X년치에 대한 데이터를 분석대상으로 잡는 limit 정책을 잡는것도 추후에 유지관리 측면에서 필요할 수 있음

d1 <- dbGetQuery(con, query) %>% tbl_df # 분석범위에 해당되는 데이터 추출 후 R session 에 준비
d1

dbDisconnect(con) # RDB 상의 데이터 추출 후 연결종료
```

```{r eval = T, echo = scriptEcho}
d2 <- d1 %>% 
  mutate(collectDate = ymd_hms(collectDate)) %>% # 날짜시각 산술을 위하여 날짜 Class 로 변형 
  rename(dt = collectDate, class = tagId) %>% # 편의상 변수명 변경
  filter(!value %in% c("false", "true")) %>% # 윗단에서 추출을 하긴 했지만, 혹시나 모르는 상태값을 가지는 관제포인트를 분석범위에서 제외하기 위해
  mutate(value = as.numeric(value), class = gsub("\\W", "_", class) %>% toupper) %>% # 관제포인트 네이밍을 정리 및 소문자로 일괄변경, 값들은 모두 연속형 값으로 변경
  group_by(byhour = floor_date(dt, "hour"), class) %>% # 관제포인트 별 한시간 단위 집계를 위한 시간내림 이후 그룹핑
  summarise(mean = mean(value, na.rm = T), n = n()) %>% ungroup %>% # 관제포인트 별 평균 및 샘플개수 계산
  arrange(class, byhour) %>% # class, byhour 변수 순으로 정렬
  group_by(class) %>% 
  mutate(mean_diff = mean - lag(mean), lag_time = byhour - lag(byhour)) %>% ungroup # 관제포인트 별 시간간격 평균 차분값 및 차분시간간격 계산
d2
```

```{r eval = T, echo = scriptEcho}
d3_1 <- d2 %>% 
  filter(grepl("^BAS", class)) %>% # "BAS" 로 시작하는 관제포인트 값
  select(byhour, class, mean) %>% # 은 한시간 평균값을 이용
  spread(class, mean) # Wide term 으로 변경
d3_1

d3_2 <- d2 %>% 
  filter(grepl("^EL", class)) %>% # "EL" 로 시작하는 관제포인트 값은
  filter(lag_time == 1, mean_diff >= 0) %>% # 한시간 간격과 정상 적산값(양의값) 그리고
  group_by(class) %>% 
  filter(mean_diff <= quantile(mean_diff, .995, na.rm = T)) %>% ungroup %>% # 관제포인트 별 초 극단치를 제거한 한시간 간격 전력 실사용 값을 이용
  select(byhour, class, mean_diff) %>% # byhour, class, mean_diff 컬럼만 선택
  spread(class, mean_diff) # Wide term 으로 변경
d3_2

d4 <- full_join(d3_1, d3_2, by = "byhour") %>% # BAS, EL 통합테이블 구성
  na.locf %>% # 결측 및 맵핑 실패로 인한 것은 LOCF(last observation carried forward; 최근값 상속) 방법으르 결측 대치
  rename(dt = byhour)
d4
```

```{r eval = T, echo = scriptEcho}
# Generate futureset for predset (LOCF after lastest date load)
d4_predset <- d4 %>% 
  filter(ymd(substr(dt, 1, 10)) == max(ymd(substr(dt, 1, 10)))) %>% 
  mutate(dt = as.POSIXct(Sys.Date() + days(1) + hours(0:23))) # 그 다음날의 예측셋을 가장최근날의 값으로 구성(이론상 하루전 데이터를 상속)
d4_predset

d5 <- bind_rows(d4, d4_predset) # 예측셋을 append
d5
```

```{r eval = T, echo = scriptEcho}
# 예측대상인 Zone 별 항온항습 전력사용량 총계값 변수 설정
d6 <- d5 %>% 
  mutate(interval = floor_date(dt, "week", week_start = 7) %--% ceiling_date(dt, "week", week_start = 7, change_on_boundary = T),
         interval = as.character(interval) %>% gsub("[[:alpha:]]", "", .) %>% gsub("\\s", "", .) %>% gsub("--", " ~ ", .)) %>% # 주간간격 파생변수 생성
  gather(class, value, -dt, -interval) %>% # long term 변환
  mutate(
    zone = case_when(
      class %in% c("EL_P2_A_1_AI17", 'EL_P2_B_1_AI17', 
                   "EL_2F_U_A1_AI84","EL_2F_U_A2_AI84",
                   "EL_2F_U_B1_AI84","EL_2F_U_B2_AI84",
                   "BAS_2F_CRAC_1_HUMI","BAS_2F_CRAC_1_HUMI_S","BAS_2F_CRAC_1_TEMP","BAS_2F_CRAC_1_TEMP_S",
                   "BAS_2F_CRAC_2_HUMI","BAS_2F_CRAC_2_HUMI_S","BAS_2F_CRAC_2_TEMP","BAS_2F_CRAC_2_TEMP_S",
                   "BAS_2F_CRAC_3_HUMI","BAS_2F_CRAC_3_HUMI_S","BAS_2F_CRAC_3_TEMP","BAS_2F_CRAC_3_TEMP_S",
                   "BAS_2F_CRAC_4_HUMI","BAS_2F_CRAC_4_HUMI_S","BAS_2F_CRAC_4_TEMP","BAS_2F_CRAC_4_TEMP_S") ~ "1",
      class %in% c("EL_P2_A_2_AI17", 'EL_P2_B_2_AI17', 
                   "EL_2F_U_A3_AI84","EL_2F_U_A4_AI84","EL_2F_U_A5_AI84",
                   "EL_2F_U_B3_AI84","EL_2F_U_B4_AI84","EL_2F_U_B5_AI84",
                   "BAS_2F_CRAC_5_HUMI","BAS_2F_CRAC_5_HUMI_S","BAS_2F_CRAC_5_TEMP","BAS_2F_CRAC_5_TEMP_S",
                   "BAS_2F_CRAC_6_HUMI","BAS_2F_CRAC_6_HUMI_S","BAS_2F_CRAC_6_TEMP","BAS_2F_CRAC_6_TEMP_S",
                   "BAS_2F_CRAC_7_HUMI","BAS_2F_CRAC_7_HUMI_S","BAS_2F_CRAC_7_TEMP","BAS_2F_CRAC_7_TEMP_S",
                   "BAS_2F_CRAC_8_HUMI","BAS_2F_CRAC_8_HUMI_S","BAS_2F_CRAC_8_TEMP","BAS_2F_CRAC_8_TEMP_S") ~ "2",
      class %in% c("EL_P2_A_3_AI17", 'EL_P2_B_3_AI17', 
                   "EL_2F_U_A6_AI84","EL_2F_U_A7_AI84",
                   "EL_2F_U_B6_AI84","EL_2F_U_B7_AI84",
                   "BAS_2F_CRAC_9_HUMI","BAS_2F_CRAC_9_HUMI_S","BAS_2F_CRAC_9_TEMP","BAS_2F_CRAC_9_TEMP_S",
                   "BAS_2F_CRAC_10_HUMI","BAS_2F_CRAC_10_HUMI_S","BAS_2F_CRAC_10_TEMP","BAS_2F_CRAC_10_TEMP_S",
                   "BAS_2F_CRAC_11_HUMI","BAS_2F_CRAC_11_HUMI_S","BAS_2F_CRAC_11_TEMP","BAS_2F_CRAC_11_TEMP_S",
                   "BAS_2F_CRAC_12_HUMI","BAS_2F_CRAC_12_HUMI_S","BAS_2F_CRAC_12_TEMP","BAS_2F_CRAC_12_TEMP_S") ~ "3",
      class %in% c("EL_P2_A_4_AI17", 'EL_P2_B_4_AI17', 
                   "EL_2F_U_A8_AI84","EL_2F_U_A9_AI84",
                   "EL_2F_U_B8_AI84","EL_2F_U_B9_AI84",
                   "BAS_2F_CRAC_13_HUMI","BAS_2F_CRAC_13_HUMI_S","BAS_2F_CRAC_13_TEMP","BAS_2F_CRAC_13_TEMP_S",
                   "BAS_2F_CRAC_14_HUMI","BAS_2F_CRAC_14_HUMI_S","BAS_2F_CRAC_14_TEMP","BAS_2F_CRAC_14_TEMP_S",
                   "BAS_2F_CRAC_15_HUMI","BAS_2F_CRAC_15_HUMI_S","BAS_2F_CRAC_15_TEMP","BAS_2F_CRAC_15_TEMP_S",
                   "BAS_2F_CRAC_16_HUMI","BAS_2F_CRAC_16_HUMI_S","BAS_2F_CRAC_16_TEMP","BAS_2F_CRAC_16_TEMP_S") ~ "4",
      class %in% c("EL_P2_A_5_AI17", 'EL_P2_B_5_AI17', 
                   "EL_2F_U_A10_AI84","EL_2F_U_A11_AI84",
                   "EL_2F_U_B10_AI84","EL_2F_U_B11_AI84",
                   "BAS_2F_CRAC_17_HUMI","BAS_2F_CRAC_17_HUMI_S","BAS_2F_CRAC_17_TEMP","BAS_2F_CRAC_17_TEMP_S",
                   "BAS_2F_CRAC_18_HUMI","BAS_2F_CRAC_18_HUMI_S","BAS_2F_CRAC_18_TEMP","BAS_2F_CRAC_18_TEMP_S",
                   "BAS_2F_CRAC_19_HUMI","BAS_2F_CRAC_19_HUMI_S","BAS_2F_CRAC_19_TEMP","BAS_2F_CRAC_19_TEMP_S",
                   "BAS_2F_CRAC_20_HUMI","BAS_2F_CRAC_20_HUMI_S","BAS_2F_CRAC_20_TEMP","BAS_2F_CRAC_20_TEMP_S") ~ "5"
      ), # Zone 맵핑
    class2 = case_when(
      grepl("^EL_P2_", class) ~ "EL_CRAC",
      grepl("^EL_2F_U_", class) ~ "EL_IT",
      grepl("^EL_LN_", class) ~ "EL_LN",
      grepl("TEMP$", class) ~ "TEMP",
      grepl("HUMI$", class) ~ "HUMI",
      grepl("TEMP_S$", class) ~ "TEMP_SET",
      grepl("HUMI_S$", class) ~ "HUMI_SET",
      grepl("^BAS_CT_12_AI[12]", class) ~ "COLLING_G",
      grepl("^BAS_CT_12_AI[34]", class) ~ "COLLING_H",
      grepl("BAS_EXT_TEMP", class) ~ "OUT_TEMP"
      ) # 관제포인트 대분류 맵핑
    ) %>% 
  select(class, class2, dt, interval, zone, everything()) %>% 
  arrange(class2, dt)
d6
```

```{r eval = T, echo = scriptEcho}
# Change wide term for trainset
d7_1 <- d6 %>% 
  filter(class2 == "EL_CRAC") %>%
  group_by(dt, zone) %>% 
  summarise(value = sum(value, na.rm = T)) %>% ungroup %>% # Zone 별 항온항습기 전력사용량 총계 계산 (for 설명변수 Y 설정)
  rename(EL_CRAC = value)
d7_1

d7_2 <- d6 %>% 
  select(dt, class, value) %>% 
  spread(class, value)
d7_2
```

```{r eval = T, echo = scriptEcho}
res <- full_join(d7_1, d7_2, by = "dt") %>% 
  select(dt, EL_CRAC, zone, everything()) %>% 
  mutate(month = lubridate::month(dt) %>% as.character %>% as.factor, # 당월 파생변수 생성 (시간에 대한 설명변수를 생성시키기 위하여)
         wday = lubridate::wday(dt, label = T) %>% as.character %>% as.factor, # 당일에 대한 요일 파생변수 생성 (시간에 대한 설명변수를 생성시키기 위하여)
         hour = lubridate::hour(dt) %>% as.character %>% as.factor, # 당일 시각 파생변수 생성 (시간에 대한 설명변수를 생성시키기 위하여)
         # season = case_when(month(dt) %in% c(11, 12, 1, 2) ~ "winter", # 12, 1, 2월은 겨울로 판단
         #                    month(dt) %in% 3:5 ~ "spring", # 3, 4, 5월은 봄으로 판단
         #                    month(dt) %in% 6:8 ~ "summer", # 6, 7, 8월은 여름로 판단
         #                    month(dt) %in% 9:10 ~ "autumn"), # 9, 10월은 가을로 판단 # 계절요소별 최소샘플이 구성되지 못하여 파생시키지 않음
         load_group = case_when(month(dt) %in% 3:10 & hour %in% c(23, 0:8) ~ "small",
                               month(dt) %in% 3:10 & hour %in% c(9, 12, 17:22) ~ "medium",
                               month(dt) %in% 3:10 & hour %in% c(10:11, 13:16) ~ "large",
                               month(dt) %in% c(11, 12, 1, 2) & hour %in% c(23, 0:8) ~ "small",
                               month(dt) %in% c(11, 12, 1, 2) & hour %in% c(9, 12:16, 20:21) ~ "medium",
                               month(dt) %in% c(11, 12, 1, 2) & hour %in% c(10:11, 17:19, 22) ~ "large")) # 부하시간대 그룹 파생변수 생성 (시간에 대한 설명변수를 생성시키기 위하여, 본 구분에 대한 rule 의 출처는 : [경, 중, 최대부하시간대별 상세사항 출처](http://cyber.kepco.co.kr/ckepco/front/jsp/CY/E/E/CYEEHP00102.jsp))

res
```

<br><br>

## Save preprocessed

```{r eval = T, echo = scriptEcho}
saveRDS(res, "output/preprocessing.rds")
```

<br><br>

## Process time

```{r eval = T, echo = scriptEcho}
proc.time()
```

<br><br>

## For Ad-hoc analysis code

```{r eval = F, echo = scriptEcho}
full_join(d3_1, d3_2, by = "byhour") %>% 
  # na.locf %>% 
  rename(dt = byhour) %>% 
  saveRDS("../output/preprocessing_d4.rds") 

# for PUE summary
pd6 <- d6 %>% 
  filter(class2 %in% c("EL_CRAC", "EL_IT", "EL_LN")) %>% 
  group_by(class2, dt) %>% 
  summarise(value = sum(value, na.rm = T)) %>% 
  spread(class2, value) %>% 
  mutate(PUE = (EL_CRAC/100 + EL_IT + EL_LN) / EL_IT)

ggplot(pd6, aes(dt, PUE)) + 
  geom_line(stat = "identity") + 
  ggtitle("PUE trend")

ggplot(pd6, aes(PUE)) + 
  geom_density() + 
  ggtitle("PUE Density plot")

pd6 %>% select(PUE) %>% summary
```